version: '3'
services:
  order-service:
    build:
      context: ./services/order-service
    ports:
      - '3001:3001'
  stock-service:
    build:
      context: ./services/stock-service
    ports:
      - '3002:3002'
  shipping-service:
    build:
      context: ./services/shipping-service
    ports:
      - '3003:3003'
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - '5432:5432'
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
