version: '3.8'
services:
  order-service:
    build:
      context: ./services/order-service
    ports:
      - '3001:3001'  # Port mapping for the order service
  stock-service:
    build:
      context: ./services/stock-service
    ports:
      - '3002:3002'  # Port mapping for the stock service
  shipping-service:
    build:
      context: ./services/shipping-service
    ports:
      - '3003:3003'  # Port mapping for the shipping service
  database:
    image: postgres
    environment:
      POSTGRES_USER: user  # User for the Postgres database
      POSTGRES_PASSWORD: password  # Password for the Postgres database
      POSTGRES_DB: orders  # Name of the database to create
    ports:
      - '5432:5432'  # Port mapping for the Postgres database
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'    # Port for RabbitMQ messaging
      - '15672:15672'  # Port for RabbitMQ management console

  # Service dependencies for ensuring startup order
  depends_on:
    order-service:
      - database
    stock-service:
      - database
    shipping-service:
      - database